[project]
name = "rust-kafka-python"
version = "0.0.0"
description = "Python modules that are called from rust"
dependencies = [
	'aiokafka',
	'pandas',
]

[build-system]
requires = [
    "setuptools >= 62.2.0"
]
build-backend = "setuptools.build_meta"
